### ISSUE TITLE
I'm getting black screen when running example app

### ISSUE THREAD

**Issue by Tushar-OP** [eliasteeny/flutter_document_scanner#2]
I'm getting black screen when running example app and it is because of the camera permission, how to fix it? I did not get any pop up for camera permission on my android phone

**Comment by eliasteeny** [comment]
I'll fix the example app to request the camera permission automatically as soon as I have free time.

In the mean time you can enable the camera permission manually by closing the app and going into the app settings from your device and allowing it and then reopen the app, the scanner should work immediately.

**Comment by Tushar-OP** [comment]
Ohkay

**Comment by onlyplaytama** [comment]
This issue appear with android 10, Simple. Just spawn request access before button scan click
