### ISSUE TITLE
After detected document, app crashed and saved 0 byte image

### ISSUE THREAD

**Issue by KenZync** [eliasteeny/flutter_document_scanner#6]
Step to reproduce (Im using vscode, android)
1. Using Flutter v2.0.1 make new project 
2. add "document_scanner: ^0.1.0" to pubspec , change minSdk to 19
3. in main.dart change` body: Center( . . . ),` to

```
body: DocumentScanner(
        onDocumentScanned: (ScannedImage scannedImage) {
          print(scannedImage.croppedImage);
          var scannedDocument = scannedImage.getScannedDocumentAsFile();
        },
      ),
```
4. Debug app (F5)
5. Manual change permission in app info (camera,storage)
6. Try detecting document, detected, circular thing showed up
7. App Crash

**Comment by eliasteeny** [comment]
@KenZync can you try that latest version :  "document_scanner: ^0.1.1" ? the app crash should be resolved.

**Comment by KenZync** [comment]
0.1.1 works fine now thankyou!
